version: '3.8'

services:
  ai-sentinel:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://sentinel:SecurePassword123@postgres:5432/sentinel_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-super-secret-key-change-in-production
      - JWT_SECRET=your-jwt-secret-key-change-in-production
      - JWT_ALGORITHM=HS256
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app
      - ./logs:/app/logs

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=sentinel_db
      - POSTGRES_USER=sentinel
      - POSTGRES_PASSWORD=SecurePassword123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=AdminSecure123!
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
    depends_on:
      - prometheus

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data: