version: '3.8' 
 
services: 
  ai-sentinel: 
    build: . 
    ports: 
      - "8000:8000" 
    environment: 
      - DATABASE_URL=$${DATABASE_URL} 
      - REDIS_URL=$${REDIS_URL} 
      - SECRET_KEY=$${SECRET_KEY} 
    env_file: 
      - .env 
