"# Test AI Model Sentinel" 
"print('Testing AI Model Sentinel Tools')" 
"try:" 
"    # ¤©  «Άο©§ ικιεΆ ικΆ¥΅" 
"    import test_phase2" 
"    print('? test_phase2 imported successfully')" 
"    # ¨ θλ μλθ §νι? ¤©  «Ά§γμ" 
"    if hasattr(test_phase2, 'main'):" 
"        test_phase2.main()" 
"except Exception as e:" 
"    print('? Error:', e)" 
