# 🚀 Enterprise AI Sentinel - Production Configuration v2.0.0
system:
  version: "2.0.0"
  environment: "production"
  
health_monitoring:
  min_data_points: 10
  health_threshold_green: 0.7
  health_threshold_yellow: 0.4

anomaly_detection:
  outlier_sigma_threshold: 3.0
  enable_multivariate_analysis: true

backup:
  enable_automated_backup: true
  backup_interval_minutes: 30