global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'production'
    application: 'ai-model-sentinel'

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'ai-sentinel'
    static_configs:
      - targets: ['ai-sentinel:8000']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: ai-sentinel:8000

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics
    params:
      format: ['prometheus']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics

  - job_name: 'node'
    static_configs:
      - targets: ['ai-sentinel:9100']
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s

remote_write:
  - url: http://thanos:10908/api/v1/receive
    queue_config:
      capacity: 10000
      max_shards: 200
      min_shards: 1
      max_samples_per_send: 1000

remote_read:
  - url: http://thanos:10908/api/v1/read
    read_recent: true